name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: rps
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest

    - name: Tag image for Docker Hub
      run: docker tag "${IMAGE_NAME}:latest" "aladdin02/${IMAGE_NAME}:latest"
      
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Push image to Docker Hub
      run: docker push "aladdin02/${IMAGE_NAME}:latest"

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Run remote deployment
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<EOF
          docker pull aladdin02/rps:latest
          docker stop rps || true && docker rm rps || true
          docker run -d --name rps -p 8080:80 aladdin02/rps:latest
        EOF
